[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[target.x86_64-unknown-none]
linker = "rust-lld"
rustflags = [
    "-C", "relocation-model=static",
]



[build]
target = "x86_64-unknown-none.json"
